version: '3.8'


services:

  social_user_auth_backend:
    container_name: social_social_user_auth
    build:
      context: ./social_user_auth
      dockerfile: Dockerfile
    command: bash -c "chmod +x ./startup.sh && ./startup.sh"
    #command: bash -c " cp env_docker.example .env && 
    #                   python manage.py makemigrations &&
    #                   python manage.py migrate &&
    #                   python manage.py collectstatic --no-input &&
    #                   gunicorn user_auth.wsgi -b 0.0.0.0:8080"
    ports:
      - 8001:8080
    volumes:
      - ./social_user_auth:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - social_user_auth_pg_db

  social_user_auth_pg_db:
    container_name: social_user_auth_pg_db
    image: postgis/postgis:13-3.1-alpine
    restart: unless-stopped
    volumes:
      - social_user_auth_pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=user_auth
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=user_auth1234
      - PGDATA:/var/lib/postgresql/data
    ports:
      - '5433:5432'
      
  social_messanger_backend:
    container_name: social_messanger
    build:
      context: ./social_messanger
      dockerfile: Dockerfile
    command: bash -c "chmod +x ./startup.sh && ./startup.sh"
    ports:
      - 8002:8080
    volumes:
      - ./social_messanger:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - social_messanger_pg_db

  social_messanger_pg_db:
    container_name: social_messanger_pg_db
    image: postgis/postgis:13-3.1-alpine
    restart: unless-stopped
    volumes:
      - social_messanger_pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=messanger_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=messanger1234
      - PGDATA:/var/lib/postgresql/data
    ports:
      - '5434:5432'
      
  social_notification_backend:
    container_name: social_notification
    build:
      context: ./social_notification
      dockerfile: Dockerfile
    command: bash -c "chmod +x ./startup.sh && ./startup.sh"
    ports:
      - 8003:8080
    volumes:
      - ./social_notification:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - social_notification_pg_db

  social_notification_pg_db:
    container_name: social_notification_pg_db
    image: postgis/postgis:13-3.1-alpine
    restart: unless-stopped
    volumes:
      - social_notification_pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=notification_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=notification1234
      - PGDATA:/var/lib/postgresql/data
    ports:
      - '5435:5432'
      
volumes:
  social_user_auth_pg_data:
    driver: local

  social_messanger_pg_data:
    driver: local

  social_notification_pg_data:
    driver: local
    
    
    
